// car-data.js
// Vehicle quality & valuation reference dataset for the Car Quality & Value Checker.
//
// Each row: [make, model, category, basePriceNew, reliability(0-10), safety(1-5 stars),
//            maintenanceTier, depreciationFactor, commonIssues[], pros[], cons[]]
//
// basePriceNew: approximate current-dollar MSRP used as the depreciation baseline.
// depreciationFactor: >1 holds value better than a typical vehicle, <1 depreciates faster.
// These figures are informed estimates for illustration, not official appraisal data.

const RAW_CAR_DATA = [
["Toyota","Camry","Sedan",28000,9.0,5,"Low",1.18,
  ["Excessive oil consumption reported on some 2007-2011 V6 engines","Infotainment touchscreen lag on 2018-2020 units"],
  ["Best-in-class reliability track record","Very low cost of ownership","Strong resale value","Comfortable and fuel-efficient"],
  ["Conservative interior design","Road noise on base LE trim"]],
["Toyota","Corolla","Sedan",22000,9.2,5,"Low",1.2,
  ["Minor CVT shudder at low speeds on some 2020-2022 models","Sluggish acceleration on base engine"],
  ["Exceptional long-term reliability","Excellent fuel economy","Very affordable to maintain","Strong safety ratings"],
  ["Base engine underpowered","Firm ride on sport trims"]],
["Toyota","RAV4","SUV",32000,8.8,5,"Low",1.2,
  ["Excessive oil consumption reported on some 2019-2020 models","Infotainment freezing on early units"],
  ["Class-leading reliability for compact SUVs","Strong resale value","Efficient hybrid variant available","Spacious cargo area"],
  ["Firm ride quality","Wind noise at highway speeds"]],
["Toyota","Highlander","SUV",40000,8.7,5,"Low",1.15,
  ["Some transmission hesitation reported on 2020-2021 models","Minor third-row water leaks on early units"],
  ["Excellent reliability for a 3-row SUV","Comfortable ride","Strong hybrid option","High resale value"],
  ["Third row tight for adults","Pricier than rivals"]],
["Toyota","Tacoma","Truck",34000,8.5,4,"Medium",1.25,
  ["Frame rust issues on 2005-2010 models (recall/buyback program existed)","Rough ride unladen"],
  ["Legendary resale value","Strong off-road capability","Reliable drivetrain","Strong towing for its class"],
  ["Cramped cabin on access cab","Dated interior tech"]],

["Honda","Civic","Sedan",24000,8.8,5,"Low",1.15,
  ["Infotainment touchscreen glitches on 2016-2018 models","AC condenser issues on some 2016-2020 units"],
  ["Excellent reliability","Fun to drive","Great fuel economy","Strong resale value"],
  ["Road noise at highway speed","Limited rear visibility on Sport trim"]],
["Honda","Accord","Sedan",28000,8.7,5,"Low",1.12,
  ["Engine oil dilution on some 2018 1.5T models (software fix issued)","Minor infotainment lag"],
  ["Refined ride and handling","Spacious interior","Strong reliability record","Efficient turbo engines"],
  ["CVT can feel rubbery under hard acceleration","Options push price up quickly"]],
["Honda","CR-V","SUV",32000,8.5,5,"Low",1.15,
  ["Oil dilution issue on 2017-2018 1.5T models in cold climates","Some AC compressor failures reported"],
  ["Best-in-class practicality","Excellent reliability","High resale value","Comfortable ride"],
  ["Turbo engine noisy under load","Base trim lacks some safety tech"]],
["Honda","Pilot","SUV",40000,8.2,5,"Medium",1.1,
  ["Transmission harshness on 2016-2019 9-speed automatic","Some cylinder-deactivation (VCM) related complaints"],
  ["Spacious 3-row seating","Strong V6 performance","Good reliability for the segment","Comfortable long-distance ride"],
  ["Below-average fuel economy","Infotainment system feels dated"]],
["Honda","Odyssey","Minivan",38000,8.0,5,"Medium",1.05,
  ["9-speed transmission shudder on 2018-2019 models","Battery drain issues on some 2018 models"],
  ["Best-in-class minivan handling","Clever interior features","Strong V6 power","Good reliability"],
  ["Transmission can feel jerky","Firm ride on Elite trim"]],

["Ford","F-150","Truck",38000,7.5,5,"Medium",1.2,
  ["Spark plug ejection issue on 2011-2014 5.4L/6.2L V8 engines","10-speed transmission shudder on some 2018-2020 models"],
  ["Best-selling truck with huge parts availability","Strong towing/payload options","Excellent resale value","Wide range of powertrains"],
  ["Options and repairs can be pricey","Some engine choices have known issues"]],
["Ford","Escape","SUV",30000,6.5,5,"Medium",0.95,
  ["1.6L EcoBoost engine fire recall on 2013-2014 models","Transmission shudder on some 2020-2021 hybrid models"],
  ["Good fuel economy options","Comfortable ride","Hybrid and PHEV variants available"],
  ["Below-average reliability history","Interior quality lags rivals"]],
["Ford","Explorer","SUV",40000,6.0,5,"High",0.9,
  ["Coolant leaks into the cabin on 2020-2021 models","Driveshaft/axle issues reported on early 2020 models"],
  ["Strong towing capacity","Available hybrid and ST performance trims","Spacious 3-row cabin"],
  ["Below-average reliability, especially early model years","Higher than average repair costs"]],
["Ford","Mustang","Coupe",32000,7.2,4,"Medium",1.05,
  ["Clutch pedal issues on manual EcoBoost models","Minor electrical gremlins in infotainment"],
  ["Iconic performance and sound","Strong resale value among enthusiasts","Wide range of trims from EcoBoost to GT"],
  ["Firm ride, limited rear visibility","Rear seat largely impractical"]],
["Ford","Focus","Hatchback",21000,5.5,5,"High",0.8,
  ["PowerShift dual-clutch transmission shudder/failure (subject of class-action lawsuits) on 2012-2016 models","Frequent clutch replacements reported"],
  ["Fun to drive","Efficient engines","Practical hatchback cargo space"],
  ["Notorious transmission reliability issues","Discontinued, parts availability shrinking"]],

["Chevrolet","Silverado 1500","Truck",38000,7.3,5,"Medium",1.15,
  ["Lifter/valvetrain ticking (AFM) on some 5.3L/6.2L V8 engines","Infotainment freezing on 2019-2021 models"],
  ["Strong towing and payload capacity","Comfortable ride for a truck","Wide engine lineup including diesel"],
  ["AFM-related engine issues on some V8s","Interior materials feel low-rent on base trims"]],
["Chevrolet","Equinox","SUV",28000,6.0,5,"Medium",0.9,
  ["1.5L turbo engine excessive oil consumption on 2018-2019 models","Timing chain wear reported on some units"],
  ["Efficient turbo engines","Spacious cabin for the class","Affordable pricing"],
  ["Below-average reliability record","Oil consumption complaints"]],
["Chevrolet","Malibu","Sedan",26000,6.2,5,"Medium",0.85,
  ["1.5L turbo timing chain stretch on some 2016-2018 models","CVT-like shift behavior in base engine"],
  ["Comfortable ride","Roomy back seat","Efficient base engine"],
  ["Bland driving dynamics","Reliability trails Japanese rivals"]],
["Chevrolet","Tahoe","SUV",55000,6.8,4,"High",1.0,
  ["Air ride suspension failures on models so equipped","Infotainment system reboots reported"],
  ["Massive cargo and towing capacity","Comfortable highway cruiser","Strong V8 power"],
  ["Poor fuel economy","Expensive to maintain and repair"]],
["Chevrolet","Camaro","Coupe",32000,7.0,4,"Medium",0.95,
  ["Poor outward visibility widely cited by owners","Infotainment glitches on early model years"],
  ["Excellent performance per dollar","Strong V8 and turbo-4 options"],
  ["Very poor visibility and practicality","Tight cabin"]],

["Nissan","Altima","Sedan",26000,5.8,4,"Medium",0.8,
  ["CVT transmission failures common on 2013-2018 models (extended warranty issued)","Oil consumption on some 2.5L engines"],
  ["Comfortable ride","Good fuel economy","Roomy interior"],
  ["CVT reliability is a significant concern","Fast depreciation"]],
["Nissan","Rogue","SUV",29000,6.0,5,"Medium",0.85,
  ["CVT shudder and failure reported on 2014-2019 models","Timing chain noise on some 2021+ 1.5T models"],
  ["Efficient and practical","Comfortable ride quality","Good value for the segment"],
  ["CVT durability concerns","Underpowered compared to rivals"]],
["Nissan","Sentra","Sedan",21000,6.3,5,"Medium",0.85,
  ["CVT judder reported on pre-2020 models","Infotainment lag on base trims"],
  ["Affordable and efficient","Improved styling and interior since 2020 redesign"],
  ["Historic CVT reliability concerns","Modest performance"]],
["Nissan","Pathfinder","SUV",38000,5.7,5,"High",0.8,
  ["CVT overheating and failure widely reported on 2013-2020 models","Timing chain rattle on V6 engine"],
  ["Good towing for the class","Comfortable third-row seating"],
  ["CVT reliability is a major concern","Below-average resale value"]],
["Nissan","Maxima","Sedan",38000,6.5,5,"Medium",0.85,
  ["CVT reliability concerns shared with Altima/Rogue platform-mates","Timing chain tensioner noise on VQ35 V6"],
  ["Sporty handling for a sedan","Strong V6 power","Upscale interior"],
  ["CVT can feel strained under hard acceleration","Fast depreciation"]],

["Hyundai","Elantra","Sedan",22000,7.0,5,"Medium",0.85,
  ["Theta II engine knock/stall recall on 2011-2018 models with 1.8L/2.0L engines","Some fuel pump recalls on newer models"],
  ["Great value and long warranty","Modern tech features","Good fuel economy"],
  ["Engine recall history on older models","Firm ride on N-Line trim"]],
["Hyundai","Sonata","Sedan",27000,7.2,5,"Medium",0.85,
  ["Theta II engine recall/lawsuit affecting 2011-2019 models","Some engine fire recalls reported"],
  ["Stylish design","Strong warranty coverage","Comfortable ride"],
  ["Engine reliability history is a real concern on used models","Depreciates faster than Japanese rivals"]],
["Hyundai","Tucson","SUV",30000,7.3,5,"Medium",0.85,
  ["Some Theta 1.6T/2.0T engine issues on 2019-2021 models","Panoramic sunroof rattles reported"],
  ["Excellent warranty (10yr/100k powertrain)","Modern styling and tech","Good value"],
  ["Engine reliability history from prior generations","Fast depreciation compared to Toyota/Honda"]],
["Hyundai","Santa Fe","SUV",35000,7.4,5,"Medium",0.85,
  ["Some engine stalling complaints on 2019-2020 2.4L/2.0T models","Minor infotainment freezing"],
  ["Comfortable and well-equipped","Strong warranty","Good safety ratings"],
  ["Resale value below Japanese competitors","Some engine reliability concerns in recent past"]],
["Hyundai","Palisade","SUV",42000,8.0,5,"Medium",0.95,
  ["Minor turbo lag/hesitation reported on early models","Some panoramic sunroof wind noise complaints"],
  ["Excellent value for a 3-row SUV","Upscale interior","Strong warranty coverage","Good reliability for a newer model"],
  ["Fast initial depreciation typical of the brand","Limited used inventory due to popularity"]],

["Kia","K5","Sedan",27000,7.2,5,"Medium",0.85,
  ["Theta II engine recall risk shared with Hyundai siblings (pre-2020 models)","Some turbo engine oil consumption reports"],
  ["Sharp styling","Strong warranty","Good value for features offered"],
  ["Shares older-generation engine reliability concerns","Fast depreciation"]],
["Kia","Forte","Sedan",21000,7.3,5,"Medium",0.85,
  ["Minor infotainment lag on base trims","Some IVT transmission hesitation reported"],
  ["Affordable and efficient","Long warranty coverage","Roomy for its class"],
  ["Base engine underpowered","Fast depreciation"]],
["Kia","Sportage","SUV",29000,7.4,5,"Medium",0.85,
  ["Some turbo engine oil consumption on 2017-2019 models","Infotainment freezing reported on early units"],
  ["Bold styling","Strong warranty","Good value and features"],
  ["Resale value trails Japanese rivals","Busy ride on rough roads"]],
["Kia","Sorento","SUV",34000,7.5,5,"Medium",0.9,
  ["Dual-clutch hybrid transmission jerkiness on some 2021+ models","Minor turbo lag"],
  ["Efficient hybrid option","Upscale cabin for the price","Strong warranty"],
  ["Third row very tight","Fast depreciation typical of the brand"]],
["Kia","Telluride","SUV",45000,8.3,5,"Medium",1.0,
  ["Minor turbo lag reported","Occasional infotainment reboot complaints"],
  ["Excellent value and features","Very strong reliability for a newer model","Spacious, comfortable 3-row cabin"],
  ["High demand can mean dealer markups","Faster initial depreciation than Toyota/Honda"]],

["Volkswagen","Jetta","Sedan",24000,6.0,5,"Medium",0.8,
  ["Timing chain tensioner failure on older 2.0T EA888 engines","Electrical sensor issues (window regulators, coil packs)"],
  ["European driving dynamics","Upscale interior for the price"],
  ["Higher repair costs than mainstream rivals","Electrical reliability concerns"]],
["Volkswagen","Passat","Sedan",27000,6.0,5,"Medium",0.8,
  ["Diesel emissions scandal affected TDI models (2009-2015)","Timing chain and electrical issues on gas models"],
  ["Spacious, comfortable cabin","Composed highway ride"],
  ["Below-average reliability","Discontinued in the US, harder resale"]],
["Volkswagen","Tiguan","SUV",30000,6.2,5,"Medium",0.8,
  ["Timing chain tensioner failures on early 2.0T engines","Electrical gremlins including window and lock issues"],
  ["Refined ride and handling","Upscale cabin materials"],
  ["Higher maintenance costs","Reliability below class average"]],
["Volkswagen","Atlas","SUV",38000,6.0,5,"High",0.8,
  ["Electrical and infotainment glitches reported across model years","Timing chain issues on 2.0T engine"],
  ["Spacious 3-row seating","Comfortable ride"],
  ["Reliability concerns and costly repairs","Fast depreciation"]],
["Volkswagen","Golf","Hatchback",24000,6.5,5,"Medium",0.8,
  ["Timing chain tensioner wear on EA888 engines (pre-2015)","Electrical sensor faults"],
  ["Excellent driving dynamics","Practical hatchback versatility"],
  ["Discontinued in the US market (GTI/R remain)","Higher repair costs than mainstream rivals"]],

["BMW","3 Series","Sedan",45000,6.5,5,"Very High",0.72,
  ["Timing chain guide failure on N20/N26 engines (2012-2015)","Costly electrical/sensor failures out of warranty"],
  ["Excellent handling and performance","Upscale interior and tech"],
  ["Very high maintenance and repair costs out of warranty","Fast depreciation"]],
["BMW","5 Series","Sedan",58000,6.3,5,"Very High",0.7,
  ["Timing chain issues on turbo four-cylinder engines","Air suspension failures on models so equipped"],
  ["Refined ride and strong performance","Luxurious, tech-forward cabin"],
  ["Expensive maintenance once out of warranty","Steep depreciation"]],
["BMW","X3","SUV",48000,6.4,5,"Very High",0.72,
  ["Timing chain tensioner wear on 2.0T engines","Electrical accessory failures common out of warranty"],
  ["Sporty handling for an SUV","Upscale cabin materials"],
  ["High repair costs out of warranty","Depreciates quickly"]],
["BMW","X5","SUV",65000,6.2,5,"Very High",0.7,
  ["Air suspension failures common on higher-mileage units","Timing chain and electrical issues on some engines"],
  ["Strong performance and refinement","Advanced tech and safety features"],
  ["Very expensive to maintain long-term","Fast depreciation after initial years"]],
["BMW","7 Series","Sedan",95000,6.0,5,"Very High",0.62,
  ["Air suspension and electronics failures common with age","Complex tech systems costly to repair"],
  ["Flagship luxury and technology","Exceptional comfort and refinement"],
  ["Among the fastest-depreciating luxury sedans","Extremely costly to maintain out of warranty"]],

["Mercedes-Benz","C-Class","Sedan",46000,6.2,5,"Very High",0.7,
  ["Balance shaft/timing chain wear on some 4-cylinder engines","Electrical module failures common out of warranty"],
  ["Upscale cabin and ride quality","Strong safety reputation"],
  ["High maintenance costs out of warranty","Fast depreciation"]],
["Mercedes-Benz","E-Class","Sedan",60000,6.0,5,"Very High",0.68,
  ["Air suspension (Airmatic) failures common with age","Electrical gremlins across infotainment and sensors"],
  ["Excellent comfort and refinement","Advanced safety technology"],
  ["Very expensive repairs once out of warranty","Steep depreciation curve"]],
["Mercedes-Benz","GLC","SUV",48000,6.1,5,"Very High",0.7,
  ["Timing chain and balance shaft wear reported","Electrical accessory faults common"],
  ["Refined ride and strong build quality","Upscale interior"],
  ["Costly maintenance long-term","Depreciates quickly after 3-4 years"]],
["Mercedes-Benz","GLE","SUV",62000,6.0,5,"Very High",0.65,
  ["Air suspension failures common on higher mileage units","Complex electronics prone to faults with age"],
  ["Comfortable and powerful","Upscale technology suite"],
  ["Very high long-term maintenance costs","Fast depreciation"]],
["Mercedes-Benz","S-Class","Sedan",115000,6.2,5,"Very High",0.6,
  ["Air suspension and complex electronics failures with age","Costly specialist repairs required"],
  ["Flagship comfort, tech, and safety","Exceptional ride quality"],
  ["Extremely expensive to maintain out of warranty","Among the fastest-depreciating luxury cars"]],

["Audi","A4","Sedan",45000,6.3,5,"Very High",0.72,
  ["Timing chain tensioner failures on EA888 engines","PCV/oil consumption issues on some model years"],
  ["Refined interior and technology","Excellent Quattro AWD available"],
  ["High maintenance costs out of warranty","Fast depreciation"]],
["Audi","A6","Sedan",62000,6.1,5,"Very High",0.68,
  ["Timing chain and carbon buildup issues on direct-injection engines","Air suspension faults on models so equipped"],
  ["Upscale, tech-forward cabin","Composed highway ride"],
  ["Expensive long-term maintenance","Steep depreciation"]],
["Audi","Q5","SUV",48000,6.2,5,"Very High",0.72,
  ["Timing chain tensioner wear reported on 2.0T engines","Carbon buildup requiring intake cleaning"],
  ["Strong Quattro AWD performance","Upscale cabin materials"],
  ["High repair costs out of warranty","Depreciates faster than Japanese/Korean rivals"]],
["Audi","Q7","SUV",65000,6.0,5,"Very High",0.65,
  ["Air suspension failures common with age","Electrical accessory faults across infotainment"],
  ["Comfortable 3-row luxury SUV","Strong towing and performance"],
  ["Very costly to maintain long-term","Fast depreciation"]],
["Audi","A3","Hatchback",36000,6.4,5,"Very High",0.75,
  ["Timing chain tensioner wear on EA888 engine","Carbon buildup on intake valves"],
  ["Fun to drive, compact luxury footprint","Upscale cabin for the size"],
  ["Costly maintenance out of warranty","Small back seat and cargo area"]],

["Subaru","Outback","SUV",30000,8.0,5,"Medium",1.1,
  ["Head gasket failures on older 2.5L EJ engines (pre-2011, largely resolved since)","CVT judder reported on some 2020-2021 models"],
  ["Standard AWD and strong safety ratings","Excellent resale value","Comfortable ride and good visibility"],
  ["CVT can feel unrefined under hard acceleration","Infotainment lag on some model years"]],
["Subaru","Forester","SUV",28000,8.2,5,"Medium",1.1,
  ["Head gasket issues largely resolved after 2011 redesign","Some oil consumption complaints on FB25 engine"],
  ["Best-in-class visibility","Standard AWD","Strong safety and reliability reputation"],
  ["Underpowered compared to turbo rivals","CVT drone under acceleration"]],
["Subaru","Impreza","Sedan",22000,7.8,5,"Medium",1.05,
  ["Minor CVT hesitation reported on some model years","Infotainment touchscreen lag on base units"],
  ["Standard AWD at an affordable price","Good reliability and safety ratings"],
  ["Underpowered base engine","Road noise at highway speeds"]],
["Subaru","Crosstrek","SUV",26000,7.9,5,"Medium",1.05,
  ["CVT judder reported on some 2018-2020 models","Minor oil consumption complaints"],
  ["Standard AWD with good ground clearance","Strong resale value","Good fuel economy for the segment"],
  ["Underpowered on the highway","Firm ride on rough pavement"]],
["Subaru","Ascent","SUV",36000,7.0,5,"Medium",0.95,
  ["CVT overheating/failure reported on some 2019-2020 models (extended warranty issued)","Turbo engine head gasket concerns reported"],
  ["Standard AWD and 3-row seating","Strong safety ratings"],
  ["CVT reliability concerns in early model years","Turbo engine can be pricier to maintain"]],

["Mazda","Mazda3","Sedan",24000,8.4,5,"Low",1.05,
  ["Minor infotainment (Mazda Connect) lag on early units","Some reports of premature brake wear"],
  ["Upscale interior for the price","Excellent driving dynamics","Strong reliability record"],
  ["Firm ride on higher trims","Limited rear visibility"]],
["Mazda","CX-5","SUV",30000,8.5,5,"Low",1.1,
  ["Minor turbocharger lag reported on early Turbo models","Infotainment controller learning curve"],
  ["Class-leading interior quality","Excellent handling for a compact SUV","Strong reliability and resale value"],
  ["Rear seat space tighter than rivals","Firm ride on Turbo trim"]],
["Mazda","CX-9","SUV",38000,8.0,5,"Medium",1.0,
  ["Minor turbo lag under load","Some reports of infotainment freezing on early units"],
  ["Upscale cabin for a mainstream 3-row SUV","Strong handling for its size","Good reliability"],
  ["Third row cramped for adults","Needs premium fuel for full power"]],
["Mazda","Mazda6","Sedan",27000,8.1,5,"Low",0.95,
  ["Minor infotainment lag on early units","Some turbo engine oil consumption reports"],
  ["Upscale styling and cabin","Strong handling and refinement"],
  ["Discontinued in the US, limited future parts network","Tight rear headroom with sunroof"]],
["Mazda","MX-5 Miata","Convertible",29000,8.6,4,"Low",1.05,
  ["Minor soft-top wear over time","Very limited cargo space (a design tradeoff, not a defect)"],
  ["Exceptional reliability for a sports car","Extremely fun to drive","Strong enthusiast resale value"],
  ["Very limited practicality","Firm ride on Club/RF trims"]],

["Jeep","Wrangler","SUV",35000,6.0,4,"High",1.35,
  ["Death wobble (steering) reported across generations","Water leaks into cabin on soft-top models","Electrical gremlins on infotainment"],
  ["Unmatched off-road capability","Exceptional resale value","Strong aftermarket support"],
  ["Below-average on-road reliability and refinement","Poor fuel economy and wind noise"]],
["Jeep","Grand Cherokee","SUV",40000,5.8,5,"High",0.85,
  ["Air suspension failures common on models so equipped","Electrical and infotainment glitches widely reported"],
  ["Comfortable and capable on- and off-road","Upscale interior on higher trims"],
  ["Below-average reliability record","Costly repairs for air suspension and electronics"]],
["Jeep","Cherokee","SUV",32000,5.5,5,"Medium",0.8,
  ["9-speed automatic transmission shudder and failure widely reported (especially 2014-2017)","Electrical gremlins reported across model years"],
  ["Good off-road capability for the class","Distinctive styling"],
  ["Transmission reliability is a significant concern","Below-average resale value"]],
["Jeep","Compass","SUV",28000,5.3,5,"Medium",0.75,
  ["9-speed transmission hesitation and shudder reported","Electrical and infotainment issues common"],
  ["Compact size with a genuine off-road Trailhawk trim","Competitive pricing"],
  ["Below-average reliability across the board","Interior materials feel low-rent"]],
["Jeep","Renegade","SUV",26000,5.2,5,"Medium",0.7,
  ["9-speed transmission shudder reported","Electrical gremlins and infotainment glitches common"],
  ["Distinctive styling and genuine off-road Trailhawk trim","Compact and easy to park"],
  ["Below-average reliability","Discontinued in the US, resale/parts concerns growing"]],

["Ram","1500","Truck",42000,7.0,5,"Medium",1.1,
  ["Air suspension failures on models so equipped","Electrical gremlins on infotainment/gauge cluster"],
  ["Class-leading ride comfort (coil-spring rear suspension)","Strong towing and available diesel/hybrid powertrains"],
  ["Air suspension repairs can be costly","Electrical reliability trails Toyota/Honda trucks"]],
["Ram","2500","Truck",52000,7.0,4,"High",1.05,
  ["DEF system issues on diesel models","Electrical gremlins reported across model years"],
  ["Excellent heavy-duty towing and payload","Strong diesel powertrain option"],
  ["Diesel emissions systems can be costly to repair","Rough ride unladen"]],
["Ram","ProMaster","Van",38000,6.5,4,"Medium",0.85,
  ["Some reports of front-wheel-drive traction issues in snow","Electrical accessory faults reported"],
  ["Excellent cargo volume and configurability","Good visibility and maneuverability for a full-size van"],
  ["Below-average reliability record","Utilitarian ride quality"]],

["GMC","Sierra 1500","Truck",42000,7.2,5,"Medium",1.1,
  ["Lifter/valvetrain ticking (AFM) on some V8 engines shared with Silverado","Infotainment freezing reported"],
  ["Upscale interior compared to Silverado sibling","Strong towing and payload capacity"],
  ["AFM-related engine issues on some V8s","Premium pricing over the mechanically similar Silverado"]],
["GMC","Yukon","SUV",58000,6.9,4,"High",1.0,
  ["Air ride suspension failures on models so equipped","Infotainment reboot issues reported"],
  ["Massive cargo and towing capacity","Upscale cabin on Denali trim"],
  ["Poor fuel economy","Expensive to maintain and repair"]],
["GMC","Terrain","SUV",30000,6.3,5,"Medium",0.85,
  ["1.5L/2.0L turbo oil consumption reported on early models","Timing chain wear reported on some units"],
  ["Distinctive styling and upscale cabin for the class","Efficient turbo engine options"],
  ["Below-average reliability record","Firm ride on higher trims"]],
["GMC","Acadia","SUV",38000,6.4,5,"Medium",0.85,
  ["Timing chain and oil consumption concerns on V6 engine","Electrical accessory faults reported"],
  ["More manageable size than full-size SUVs with V6 power","Upscale interior available"],
  ["Below-average reliability record","Third row very tight"]],

["Tesla","Model 3","Sedan",42000,7.0,5,"Medium",0.85,
  ["Panel gap and paint quality inconsistencies reported","Suspension component wear (control arms) on early production"],
  ["Exceptional performance and efficiency","Minimal scheduled maintenance (no oil changes)","Frequent over-the-air software improvements"],
  ["Build quality inconsistent, especially early production","Service center availability limited in some regions"]],
["Tesla","Model Y","SUV",48000,7.1,5,"Medium",0.85,
  ["Panel gap and trim rattle complaints reported","Suspension noise/wear reported on some early units"],
  ["Strong performance and efficiency","Spacious cargo with frunk","Continuous software feature updates"],
  ["Build quality inconsistencies reported","Repair costs and parts availability can be high after accidents"]],
["Tesla","Model S","Sedan",90000,6.8,5,"High",0.75,
  ["Drive unit and suspension component replacements reported on higher-mileage units","MCU (media control unit) failures on early models"],
  ["Exceptional performance and range","Cutting-edge technology"],
  ["High repair costs out of warranty","Fast depreciation as newer models are released"]],
["Tesla","Model X","SUV",95000,6.5,5,"High",0.7,
  ["Falcon-wing door sensor and alignment issues widely reported","Air suspension faults reported"],
  ["Unique falcon-wing doors and strong performance","Spacious interior with high-tech features"],
  ["Falcon doors add complexity and repair cost","Among the faster-depreciating Teslas"]],

["Lexus","RX","SUV",48000,8.8,5,"Low",1.1,
  ["Minor infotainment controller learning curve on older trackpad/mouse interface","Very few significant mechanical complaints"],
  ["Outstanding reliability for a luxury SUV","Comfortable, quiet ride","Strong resale value"],
  ["Infotainment interface historically less intuitive","Conservative styling on older generations"]],
["Lexus","ES","Sedan",42000,8.9,5,"Low",1.1,
  ["Very few reported mechanical issues","Minor infotainment controller learning curve"],
  ["Exceptional reliability and low ownership costs","Quiet, comfortable ride","Strong resale value"],
  ["Not very engaging to drive","Conservative styling"]],
["Lexus","NX","SUV",40000,8.3,5,"Low",1.0,
  ["Minor infotainment lag on early models","Firm ride reported on F Sport trim"],
  ["Strong reliability and low maintenance costs","Upscale cabin materials"],
  ["Cramped rear seat and cargo area on first-gen models","Firm ride on sport trim"]],
["Lexus","GX","SUV",58000,8.4,4,"Low",1.15,
  ["Firm, truck-like ride quality (a design tradeoff, not a defect)","Very few significant mechanical complaints"],
  ["Exceptional off-road capability and durability","Strong resale value","Land Cruiser-based reliability"],
  ["Poor fuel economy","Truck-like ride and handling on-road"]],

["Dodge","Charger","Sedan",36000,6.5,5,"Medium",0.9,
  ["8-speed transmission hesitation reported on some V6 models","Electrical gremlins on infotainment"],
  ["Available V8 Hemi performance and RWD/AWD options","Spacious sedan cabin with strong straight-line performance"],
  ["Below-average fuel economy on V8 models","Reliability trails mainstream sedans"]],
["Dodge","Challenger","Coupe",38000,6.6,4,"Medium",0.95,
  ["8-speed transmission hesitation on some V6/V8 models","Electrical gremlins reported"],
  ["Iconic muscle car styling and Hemi V8 power","Strong enthusiast resale value on performance trims"],
  ["Poor rear visibility and practicality","Below-average fuel economy"]],
["Dodge","Durango","SUV",42000,6.4,5,"High",0.85,
  ["Air suspension and electrical faults reported on higher trims","8-speed transmission hesitation reported"],
  ["Strong towing capacity with available V8/Hemi","Comfortable 3-row seating"],
  ["Below-average fuel economy","Reliability trails class leaders"]],

["Volvo","XC90","SUV",58000,6.7,5,"Very High",0.75,
  ["Electrical/infotainment glitches reported across model years","Air suspension faults on models so equipped"],
  ["Best-in-class safety technology and reputation","Upscale, minimalist Scandinavian interior"],
  ["Costly maintenance out of warranty","Infotainment system can be glitchy"]],
["Volvo","XC60","SUV",48000,6.8,5,"Very High",0.75,
  ["Electrical gremlins reported on infotainment and sensors","Minor turbo/supercharger belt noise reported"],
  ["Excellent safety ratings","Upscale, understated cabin design"],
  ["Higher maintenance costs out of warranty","Depreciates faster than Japanese luxury rivals"]],
["Volvo","S60","Sedan",42000,6.6,5,"Very High",0.72,
  ["Electrical and infotainment glitches reported","Minor turbo lag on base engine"],
  ["Strong safety reputation","Distinctive Scandinavian design"],
  ["Higher maintenance costs","Limited dealer network compared to mainstream brands"]],

["Porsche","911","Coupe",115000,8.0,5,"Very High",1.0,
  ["IMS bearing failure risk on pre-2009 models only (largely resolved in later generations)","Very costly specialist maintenance regardless of issues"],
  ["Exceptional engineering and driving experience","Strong resale value among sports cars","Surprisingly reliable for a performance car"],
  ["Extremely expensive routine maintenance and parts","Impractical rear seats"]],
["Porsche","Cayenne","SUV",78000,6.8,5,"Very High",0.78,
  ["Air suspension failures common with age","Coolant pipe (plastic) failures on V6/V8 engines"],
  ["Excellent performance and handling for an SUV","Upscale cabin and build quality"],
  ["Very expensive to maintain out of warranty","Fast depreciation relative to purchase price"]],
["Porsche","Macan","SUV",62000,6.9,5,"Very High",0.75,
  ["Coolant pipe and water pump failures reported","Air suspension faults on models so equipped"],
  ["Sports-car-like handling in an SUV package","Upscale interior and strong build quality"],
  ["Costly specialist maintenance","Fast depreciation"]],

["Land Rover","Range Rover","SUV",105000,4.5,5,"Very High",0.62,
  ["Air suspension failures very common and costly","Electrical gremlins across infotainment, sensors, and climate control widely reported"],
  ["Unmatched luxury off-road capability","Prestigious brand and comfortable ride"],
  ["Among the worst reliability records of any luxury SUV","Extremely costly and frequent repairs"]],
["Land Rover","Range Rover Sport","SUV",82000,4.6,5,"Very High",0.62,
  ["Air suspension failures widely reported","Electrical and infotainment reliability issues common"],
  ["Strong off-road capability with sporty on-road manners","Upscale cabin"],
  ["Poor reliability reputation","Very high repair costs out of warranty"]],
["Land Rover","Discovery","SUV",68000,4.7,5,"Very High",0.62,
  ["Air suspension and electrical faults widely reported","Infotainment system reliability concerns"],
  ["Excellent off-road and towing capability","Versatile, spacious interior"],
  ["Below-average reliability across the lineup","Costly and frequent repairs reported by owners"]],

["Mitsubishi","Outlander","SUV",30000,6.5,5,"Medium",0.75,
  ["CVT hesitation and shudder reported on some model years","Infotainment lag on base trims"],
  ["Long warranty coverage (10yr/100k powertrain)","Available third row and PHEV variant"],
  ["CVT reliability concerns reported","Fast depreciation and smaller dealer network"]],
["Mitsubishi","Eclipse Cross","SUV",27000,6.3,5,"Medium",0.7,
  ["CVT hesitation reported on some models","Turbo engine oil consumption reports"],
  ["Distinctive styling","Long warranty coverage"],
  ["Below-average reliability and resale value","Cramped rear cargo area"]],

["Buick","Enclave","SUV",46000,6.6,5,"Medium",0.85,
  ["Timing chain and oil consumption concerns shared with GMC Acadia platform-mates","Electrical accessory faults reported"],
  ["Quiet, comfortable ride","Upscale interior for the price"],
  ["Below-average reliability record","Third row tight for adults"]],
["Buick","Encore","SUV",27000,6.4,5,"Medium",0.8,
  ["1.4L turbo timing chain wear reported","Minor electrical accessory faults"],
  ["Compact and easy to park","Quiet cabin for the class"],
  ["Underpowered engine","Below-average reliability"]],

["Cadillac","Escalade","SUV",78000,6.7,4,"High",0.9,
  ["Air ride suspension failures on models so equipped","Infotainment (CUE) system reliability complaints on older models"],
  ["Prestigious full-size luxury SUV with strong towing","Comfortable, tech-forward cabin"],
  ["Very expensive to maintain and repair","Poor fuel economy"]],
["Cadillac","XT5","SUV",48000,6.5,5,"Medium",0.8,
  ["Timing chain wear reported on V6 engine","Infotainment touchscreen reliability complaints"],
  ["Upscale cabin and ride quality","Strong V6 performance"],
  ["Below-average reliability for the segment","Fast depreciation relative to purchase price"]],

["Acura","MDX","SUV",50000,8.0,5,"Medium",1.0,
  ["9-speed transmission harshness reported on 2014-2019 models","Some VCM cylinder-deactivation shudder reported"],
  ["Strong reliability for a luxury SUV","Comfortable 3-row seating","Good resale value"],
  ["Transmission can feel jerky at low speeds","Dual-screen infotainment dated on older models"]],
["Acura","RDX","SUV",44000,8.1,5,"Medium",1.0,
  ["Minor turbo lag reported on early 2019+ models","Infotainment touchpad control has a learning curve"],
  ["Sharp handling for a luxury SUV","Strong reliability record","Upscale cabin"],
  ["Firm ride on A-Spec trim","Touchpad infotainment control divisive"]],
["Acura","TLX","Sedan",42000,7.9,5,"Medium",0.95,
  ["Minor infotainment touchpad learning curve","Some turbo engine oil consumption reports on early models"],
  ["Engaging handling for the segment","Strong reliability record"],
  ["Cramped rear seat on first-generation models","Touchpad control system divisive"]],

["Infiniti","Q50","Sedan",44000,6.5,5,"Medium",0.75,
  ["Transmission concerns shared with Nissan platform-mates on some trims","Electrical gremlins on dual-screen infotainment"],
  ["Strong turbo V6 performance options","Sporty handling for a luxury sedan"],
  ["Below-average reliability reputation","Fast depreciation"]],
["Infiniti","QX60","SUV",48000,6.3,5,"Medium",0.72,
  ["CVT overheating and failure concerns shared with Nissan Pathfinder platform-mate","Infotainment system reliability complaints"],
  ["Comfortable 3-row seating","Upscale cabin materials"],
  ["CVT reliability is a significant concern","Fast depreciation"]],

["MINI","Cooper","Hatchback",28000,5.8,4,"Very High",0.7,
  ["Timing chain tensioner and water pump failures common on turbo engines","Electrical gremlins widely reported"],
  ["Distinctive go-kart-like handling","Fun, characterful styling"],
  ["Below-average reliability and high repair costs","Cramped rear seat and limited cargo space"]],

["Chrysler","Pacifica","Minivan",40000,6.8,5,"High",0.75,
  ["9-speed transmission hesitation reported on early models","Electrical gremlins including battery drain on Hybrid models"],
  ["Excellent features and available hybrid powertrain","Comfortable, well-equipped cabin"],
  ["Below-average reliability record","Fast depreciation"]],
["Chrysler","300","Sedan",38000,6.5,5,"Medium",0.75,
  ["8-speed transmission hesitation reported on some V6 models","Electrical accessory faults reported"],
  ["Distinctive full-size sedan with available V8 power","Comfortable highway cruiser"],
  ["Below-average reliability and dated platform","Fast depreciation"]]
];

const CAR_DATABASE = RAW_CAR_DATA.map(function (row) {
  return {
    make: row[0],
    model: row[1],
    category: row[2],
    basePriceNew: row[3],
    reliability: row[4],
    safety: row[5],
    maintenanceTier: row[6],
    depreciationFactor: row[7],
    commonIssues: row[8],
    pros: row[9],
    cons: row[10]
  };
});
